### ISSUE TITLE
Is it just me or the ISS Pass Times API is giving incorrect predictions?

### ISSUE THREAD

**Issue by dan-german** [open-notify/Open-Notify-API#15]
When comparing the results of ISS Pass Times with the official nasa website [Spot The Station](https://spotthestation.nasa.gov/), both the quantity per day, time and duration of pass times are off. 

I've tried applying different coordinates for different locations, but nothing works.

**Comment by MDStebel** [comment]
Yes, it's way off. Nathan is aware and advised me that he's investigating.

**Comment by dan-german** [comment]
@MDStebel Got any updates? When can we expect it to be fixed?

**Comment by MDStebel** [comment]
@natronics please advise.

**Comment by natronics** [comment]
Okay, I think I got it.

The original problem was with the script that grabs new orbit data. It started (silently) failing while ago when NASA switched to HTTPS only for the resources. As time went on the stale data made the prediction worse and worse.  I fixed that, but I thought the pass times were still wrong, however it turns out my testing tool was wrong (timezones)!

I've been checking against a couple of other sources and fixed my testing tool. So it looks like it's making correct predictions again (at least as well as I can manage, it's always plus/minus a couple of minutes because of orbit uncertainty)

**Comment by MDStebel** [comment]
Great! I'll let you know if I find any issues.
Appreciate it!
Thanks
